name: Checks

on: 
  [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.13"

      - name: Install the project
        run: uv sync --locked --dev

      - name: Linting
        run: uv run ruff check --fix --diff --output-format github

      - name: Typechecking
        run: uv run pyrefly check

      - name: Formatting
        run: uv format --diff

      - name: Run tests
        run: uv run pytest
